[build]
  publish = "public/"
  command = "npm run build"

[build.processing]
  skip_processing = true

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false --legacy-peer-deps"
  GATSBY_CPU_COUNT = "2"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[plugins]]
  package = "@netlify/plugin-gatsby"

[template.environment]
  PRISMIC_ACCESS_TOKEN = "Replace with your Prismic access token"
  PRISMIC_CUSTOM_TYPES_API_TOKEN = "Replace with your Prismic custom types API token" 