backend:
  name: github
  repo: kylorobs/code_imagined
  branch: main

media_library:
  name: cloudinary
  config:
    cloud_name: the-great-sync
    api_key: 296358997549996

local_backend: true
media_folder: static/img
public_folder: /img
site_url: https://thegreatsync.com/

collections:
  - name: posts
    label: Posts
    folder: "src/pages/posts"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: tag, label: Tag }
      # - { label: "Banner", name: "banner", widget: "image" }
      - { name: body, label: Body, widget: markdown }
      - label: 'Body Image'
        name: 'image'
        widget: 'image'
        required: false
        tagname: ''
        media_library:
          config:
            default_transformations:
              - fetch_format: auto
                width: 800    
                quality: auto
                crop: fill