backend:
  name: github
  repo: kylorobs/code_imagined
  branch: main
media_folder: static/images/uploads
public_folder: /images/uploads
site_url: https://thegreatsync.com/
collections:
  - name: posts
    label: posts
    folder: posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: tag, label: Tag }
      # - { label: "Banner", name: "banner", widget: "image" }
      - { name: body, label: Body, widget: markdown }